
All:
	clear
	javac  -cp .:hsqldb.jar comp3350/wwsys/presentation/CLI.java
	java -cp .:hsqldb.jar comp3350.wwsys.presentation.CLI

build:
	javac comp3350/wwsys/presentation/CLI.java
clean:
	rm comp3350/wwsys/business/*.class
	rm comp3350/wwsys/objects/*.class
	rm comp3350/wwsys/persistence/*.class
	rm comp3350/wwsys/application/*.class
	rm comp3350/wwsys/presentation/*.class
	rm comp3350/wwsys/persistence/stub/*.class
	rm comp3350/wwsys/persistence/hsqldb/*.class

